language: C++

matrix:
  include:
    - os: osx
      #env: CONFIG=Release
      compiler: clang
      osx_image: xcode8.3

    - os: linux
      dist: trusty
      sudo: required
      #env: CONFIG=Release
      compiler: gcc
    


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      #Qt 5.9.1    
      # https://launchpad.net/~beineri/+archive/ubuntu/opt-qt59-trusty
      sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y &&
      sudo apt-get update -qq
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update &&
        brew upgrade cmake &&
        brew install qt5 &&
        chmod -R 755 /usr/local/opt/qt5/*
    fi
install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get -y install qt59-meta-full
        sudo apt-get -y install qt59-meta-dbg-full
        sudo apt-get -y install qt59creator
        sudo apt-get -y install qtdeclarative5-dev
        qmake -v
    fi
script:
  - mkdir build && cd build
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        cmake .. &&
        cmake --build .
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        cmake -D CMAKE_PREFIX_PATH=$(brew --prefix qt5) .. &&
        cmake --build .
    fi